### ISSUE TITLE
meta title、descriptionをnew, indexページの分を作成する

### ISSUE THREAD

**Issue by masanarih0ri** [masanarih0ri/sleeple#16]
## Why
* SEO対策
* シェアした際のOGPにも関連するので

## What
* metaタグ関連の設定を行う
* このタスクではOGPの対応はしない（まだ画像がないため）

## Acceptance Criteria
- [x] meta title、meta descriptionの出力がindexページでできている
- [x] meta title、meta descriptionの出力がnewページでできている
- [x] indexページの title タグは デフォルトの文字列にプラスして「睡眠習慣ログの一覧」という文言が付いている
- [x] newページの title タグは デフォルトの文字列にプラスして「睡眠習慣ログの作成」という文言が付いている
